[tool.flet]
# 不要写 path，让 flet 自动扫描根目录
assets_dir = "assets"

[tool.flet.app]
# 这里的 path 指向包含 main.py 的文件夹，"." 代表当前目录
path = "."

[tool.flet.android]
package_name = "com.xiaoying.thmx"
build_number = 1
version = "1.0.0"
# 预先增加权限，防止后续功能受限
permissions = ["INTERNET", "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE"]
